---
title: "data wrangling 2"
author: Pallavi Krishnamurthy
output: github_document
---
```{r set-up, include = FALSE}
library(tidyverse)
library(rvest)
library(httr)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Restaurant inspections

```{r}
api_url = "https://data.cityofnewyork.us/resource/43nn-pn8j.csv"

rest_inspections = 
  GET(api_url, query = list("$limit" = 50000)) %>% 
  content("parsed")
```


```{r}
rest_inspections %>% 
  count(boro, grade) %>% 
  pivot_wider(names_from = grade, values_from = n)
```

```{r}
rest_inspections %>% 
  filter(grade %in% c("A", "B", "C"), boro != "0")
```

Let's look at pizza places. 

```{r}
rest_inspections %>%
  mutate(dba = str_to_upper(dba)) %>% 
  filter(str_detect(dba, "PIZZA"))
```

```{r}
rest_inspections %>%
  mutate(dba = str_to_upper(dba)) %>% 
  filter(str_detect(dba, "PIZZA")) %>% 
  count(boro, grade) %>% 
  pivot_wider(names_from = grade, values_from = n)

```

```{r}
rest_inspections %>% 
  mutate(dba = str_to_upper(dba)) %>% 
  filter(str_detect(dba, "PIZZ")) %>% 
  mutate(
    boro = fct_infreq(boro),
    boro = str_replace(boro, "Brooklyn", "Hipster")) %>% 
  ggplot(aes(x = boro)) +
  geom_bar()
```

## Napoleon Dynamite

Get some reviews from Amazon

```{r}
nap_dyn_url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

napoleon_html = read_html(nap_dyn_url)

review_titles =
  napoleon_html %>% 
  html_nodes(".a-text-bold span") %>% 
  html_text()

review_text =
  napoleon_html %>% 
  html_nodes(".review-text-content span") %>% 
  html_text()

nap_df = 
  tibble(
  titles = review_titles,
  text = review_text
)
```





